permalink: /:categories/:title/
pygments: true
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
authors:
  garthdb:
    display_name: Garth Braithwaite
    gravatar: b5cf6e112eeee572d722743dea924487
    email: garthdb@gmail.com
    web: http://www.garthdb.com/
    twitter: garthdb
    github: garthdb
