permalink: /:categories/:title/
pygments: true
url: http://opensourcedesign.is
name: Open Source Design
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
authors:
  garthdb:
    display_name: Garth Braithwaite
    gravatar: b5cf6e112eeee572d722743dea924487
    email: garthdb@gmail.com
    web: http://www.garthdb.com/
    twitter: garthdb
    github: garthdb
    bio: 'Engineer at Adobe working on <a href="http://www.topcoat.io">Topcoat</a>.'
