permalink: /:categories/:title/
highlighter: true
url: http://designopen.org
name: Open Source Design
excerpt_separator: <!--more-->
markdown: kramdown
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: true
post:
  template: _post.txt
  extension: md
resource:
  template: _resource.txt
  extension: md
page:
  template: _page.txt
  extension: md
authors:
  garthdb:
    display_name: Garth Braithwaite
    gravatar: b5cf6e112eeee572d722743dea924487
    email: garthdb@gmail.com
    web: http://www.garthdb.com/
    twitter: garthdb
    github: garthdb
    bio: 'Hybrid at Adobe. Host of <a href="http://webfriends.io">Web Friends</a>.'
  ttimsmith:
    display_name: Tim Smith
    gravatar: febbffcb54abe1be1435720fc2268237
    email: smith@ttimsmith.com
    web: http://theboldreport.net
    twitter: ttimsmith
    github: ttimsmith
    bio: 'Designer who codes, blabber mouth, and coffee addict.'
  areus:
    display_name: Areus Wade
    gravatar: 3a88629dd9417c822b68af4af685b782
    email: hi@areuswade.com
    web: http://areuswade.com
    twitter: areus
    github: areus
    bio: 'Designer in San Diego building <a href="http://areus.co/pctg">precomposed stuff</a>.'
  terracomma:
    display_name: Christopher Moody
    gravatar: 80d7c270dfac1d947d2b3fd39bf70b6a
    email: terracomma@gmail.com
    web: http://terracomma.com
    twitter: terracomma
    github: terracomma
    bio: 'Designer and Developer currently writing code at <a href="http://wedgies.com">Wedgies</a>'
  vitorio:
    display_name: Vitorio Miliano
    gravatar: 1b2ea3fc983558c15216a609af35f709
    email: email_re_designers_opensource@vitor.io
    web: http://vitor.io
    twitter: vitor_io
    github: vitorio
    bio: 'User experience and interaction designer. I like talking about genuine outbreaks of the future.'
  mrondina:
    display_name: Mark Rondina
    gravatar: 48f5bbc2752b434e2b6d0ec263da193e
    email: mark@rondina.net
    web: http://www.markrondina.com/
    twitter: mrondina
    github: mrondina
    bio: 'Interactive designer working in web, games and mobile development.'

resourceTags: ["benefits", "blog", "challenges", "community", "design", "education", "example", "opendesign", "source"]
