permalink: /:categories/:title/
pygments: true
url: http://opensourcedesign.is
name: Open Source Design
excerpt_separator: <!--more-->
markdown: kramdown
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: true
post:
  template: _post.txt
  extension: md
resource:
  template: _resource.txt
  extension: md
page:
  template: _page.txt
  extension: md
authors:
  garthdb:
    display_name: Garth Braithwaite
    gravatar: b5cf6e112eeee572d722743dea924487
    email: garthdb@gmail.com
    web: http://www.garthdb.com/
    twitter: garthdb
    github: garthdb
    bio: 'Engineer at Adobe working on <a href="http://www.topcoat.io">Topcoat</a>.'
  ttimsmith:
    display_name: Tim Smith
    gravatar: febbffcb54abe1be1435720fc2268237
    email: smith@ttimsmith.com
    web: http://theboldreport.net
    twitter: ttimsmith
    github: ttimsmith
    bio: 'Designer who codes, blabber mouth, and coffee addict.'
  areus:
    display_name: Areus Wade
    gravatar: 3a88629dd9417c822b68af4af685b782
    email: hi@areuswade.com
    web: http://areuswade.com
    twitter: areus
    github: areus
    bio: 'Designer in San Diego building <a href="http://areus.co/pctg">precomposed stuff</a>.'
