name: Open Source Design
description: We think the best way to improve the design industry is to work in the open.
url: http://opendesign.foundation
permalink: /:categories/:title/
highlighter: rouge
excerpt_separator: <!--more-->
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Rakefile
  - README.md
  - CONTRIBUTING.md
  - LICENSE
sass:
  sass_dir: _sass
  style: compressed
# _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
post:
  template: _templates/post.txt
  extension: md
resource:
  template: _templates/resource.txt
  extension: md
page:
  template: _templates/page.txt
  extension: md

resourceCategories: ["philosophy", "sources", "redesigns", "inspiration", "tutorials", "showcase"]
